### ISSUE TITLE
Duplicate Addons?

### ISSUE THREAD

**Issue by bladehawkz** [cairthenn/Redirect#1]
Not to sound terrible, but isn't the functionally of this plugin the same as UnknownX7's ReAction (which is also a MOAction replacement).

Not sure if it's worth to continue developing this instead of adding things to his plugin instead.

**Comment by cairthenn** [comment]
I'm not sure. I wrote an addon to do a thing that I wanted and learn about the game's internals. I wasn't aware of this plugin and mine works great already :) ty though
