### ISSUE TITLE
Ground targeted abilities set to Target no longer work on hostile targets

### ISSUE THREAD

**Issue by nashutal** [cairthenn/Redirect#19]
Hi, thank you for your work! I ran across a new bug after the most recent update. Before you could set ground-targeted abilities like Eruption, Bomb Toss, Asylum, etc. to be cast on target and it would cast on the target regardless of whether they were friendly or hostile. However, after the latest update, they'll only work if you're targeting a friendly target, even for hostile actions like BLU's Eruption and Bomb Toss.

I've done a bit of testing and casting on hostile targets still works with an in-game macro like `/ac Eruption <t>` and the issue with Redirect still happens if you disable all other addons. :)

**Comment by cairthenn** [comment]
Thanks, should be fixed later today
