### ISSUE TITLE
Game crash upon using Cursor redirect

### ISSUE THREAD

**Issue by vkyfox** [cairthenn/Redirect#25]
Hello! I've noticed a crash I could cause reliably with the Redirect plugin, so I thought it could help sharing my testing here.

I was doing Leviathan for Khloe and I could reliably make my FFXIV crash by using Shukuchi with the Redirect plugin set as Cursor during combat. 
I tried using Shukuchi in the arena before starting the fight, and it did not cause a crash. 
I also went in with monk who has Thunderclap set to Model Mouseover and using it did not cause a crash (I made sure the input used the Model Mouseover redirect by manually untargetting first).
I then set up whm to use Asylum as Cursor too, went back to leviathan, started the fight and it caused the crash as well. Using it with Cursor outside of combat does not crash the game.
Just to be sure, I went into another instance (The Cloud Decks (Extreme)), started the encounter and using Asylum as Cursor crashed the game just as surely.

When I came to the github, I saw issues #18 and #9 that could be linked to this problem, as I am using both new in-game options to place Ground-Targeted AoEs ; so I went in again and did the same tests after disabling them, but the crash happened all the same.

Hoping this helps, if you have any questions please let me know!

**Comment by cairthenn** [comment]
I've tried to recreate this many times and I can't seem to regardless of the game's settings. It's possible that there's a strange interaction with another plugin you have loaded. Does this happen with only Redirect loaded? If you're able to provide your `dalamud.log` that may offer some insight.

**Comment by Sykel** [comment]
It's a conflict with FlyTextFilter, i believe? I spent half an hour trying to repro it after disabling everything. Glad there's a workaround but I don't know why it's this one.

**Comment by vkyfox** [comment]
I don't use FlyTextFilter personally. I tried disabling Damage Info which seemed a close enough candidate, to no avail.

After some more testing, Sound Filter seems to be causing the issue for me. I use it to filter out the confirmation sounds when pressing a hotbar-bound key (116) and when finishing a cast (111). When I tried uninstalling the plugin, the crash didn't occur, reinstalling it made me crash again. Disabling the two filters was not enough to prevent the crashed, so I'm assuming there must be something in common between FlyTextFilter and Sound Filter in their inherent functioning that must conflict with that of Redirect?

**Comment by joker-119** [comment]
I don't use FlyTextFilter or SoundFilter and it's happening to me aswell. Sounds like cursor redirect is fundamentally broken in some way that's causing conflicts when it shouldn't.

**Comment by NeXzRo** [comment]
i also had the same issue, after disabling SoundFilter my game didn't crash once

**Comment by neuralwiles** [comment]
This is happening for me as well, and I don't use FlyTextFilter or SoundFilter (or any 3rd party plugins). It doesn't seem to happen all of the time, but I haven't been able to pinpoint exactly what determines if it'll crash or not.

**Comment by Matuno** [comment]
Does this help?
Fatal error. Internal CLR error. (0x80131506)
   at Redirect.GameHooks.GroundActionAtCursor(IntPtr, FFXIVClientStructs.FFXIV.Client.Game.ActionType, UInt32, UInt64, UInt32, UInt32, UInt32, Void*)
   at Redirect.GameHooks.TryActionCallback(IntPtr, FFXIVClientStructs.FFXIV.Client.Game.ActionType, UInt32, UInt64, UInt32, UInt32, UInt32, Void*)
   at Dalamud.Game.Framework.HandleFrameworkUpdate(IntPtr)
