### ISSUE TITLE
Update for patch 6.3!

### ISSUE THREAD

**Issue by wirchtalksgames** [cairthenn/Redirect#40]
I don't know if you're still active in the game, but FFXIV just updated to 6.3 and was wondering if this plugin will be updated for this version. Many of us who use this awesome tool will be thrilled to keep enjoying it moving forward!

**Comment by erickt420** [comment]
There is already a pull request with the fix. Cairthenn just needs to merge the change. Playing healer is the worst thing ever without this plugin, seriously. :)

**Comment by wirchtalksgames** [comment]
Thanks! I wanted to try and updated that pull request manually but couldn't figure out how to do it lol. Guess I'll wait for the merge.

Cheers!
