### ISSUE TITLE
pluginmaster.json not found

### ISSUE THREAD

**Issue by monkeymc** [cairthenn/Redirect#43]
[https://raw.githubusercontent.com/cairthenn/CairDalamudPlugins/main/pluginmaster.json](https://raw.githubusercontent.com/cairthenn/CairDalamudPlugins/main/pluginmaster.json)

**Comment by cairthenn** [comment]
I've removed my private plugin repository for various reasons, please delete it from your custom repository list and download the plugin from Dalamud directly.

Thanks!
