### ISSUE TITLE
Magitek Armor in Praetorium Issue

### ISSUE THREAD

**Issue by IronEleven** [cairthenn/Redirect#49]
The magitek Armor's ground target AoE move goes off instantly centered on your character when clicked early with this plugin enabled, completely bypassing the ground targeting.

**Comment by Reggie2001** [comment]
I've been having the same issue, and the glitch extends to other ground targeted abilities such as BLU's Loom.

I've experimented a lot trying to figure out what causes it, as it sometimes occurs and sometimes doesn't. From what I can tell, the abilities work correctly if you use them prior to engaging an enemy. Once an enemy has aggro on you, the glitch begins. I've tried all combinations of plugin and in-game settings and cannot get the glitch to go away.

**Comment by SDPhantom** [comment]
I had a similar problem where it would target random mobs or even party members despite having all ground targeting options disabled.
