### ISSUE TITLE
Update for patch 6.5

### ISSUE THREAD

**Issue by Krojack** [cairthenn/Redirect#53]
Are there plans to update this for patch 6.5? If so I'll wait, if not I'll start looking for a replacement plugin.

**Comment by TheGokki** [comment]
Give the devs a bit of time to update on their volunteered unpaid time.

**Comment by Krojack** [comment]
> Give the devs a bit of time to update on their volunteered unpaid time.

Yes I know. I just like some sort of message saying "yes this will be update but I'm busy now so it will be a few days/weeks" or something. That way people like me know and can wait. If they aren't going to update let us know so we can look for a replacement rather than be left hanging wondering. That's all I ask.

The dev for "MOAction" said they will update but it will take a week due to IRL things. That's a good developer. Communication helps communities stay chill.
