### ISSUE TITLE
[bug] Pictomancer Starry Muse cannot queue correctly

### ISSUE THREAD

**Issue by lwins-lights** [cairthenn/Redirect#62]
How to replay the bug:
- Check all four options in "Allow these actions to queue"
- Use PCT to cast the Starry Sky Motif and then engage in the battle
- Hardcast any spell and immediately follow by using (queuing) Starry Muse
- An error will show as "Target is not in range".

Note that Starry Muse is an ogcd that does not target anything so this is a bug. Interestingly, if we do not queue it but use it when we are not casting, everything works normally.

**Comment by cairthenn** [comment]
#61
